;; php style
;(load-library "php-mode")
;(autoload 'php-mode "php-mode" "Major mode for editing php code." t)
(setq php-mode-force-pear t)
(add-hook 'php-mode-hook
	  '(lambda ()
;	     (require 'php-completion)
;	     (php-completion-mode t)
;	     (when (require 'auto-complete nil t)
;	     (make-variable-buffer-local 'ac-sources)
;	     (add-to-list 'ac-sources 'ac-source-php-completion)
;	     (auto-complete-mode t))
             (c-set-style "stroustrup")
             (c-set-offset 'inline-open 0)
             (c-set-offset 'topmost-intro 0)
             (c-set-offset 'defun-block-intro '+)
             (c-set-offset 'statement 0)
             (c-set-offset 'statement-block-intro '+)
             (c-toggle-hungry-state 1)
             (setq tab-width 4)
             (setq c-basic-offset tab-width)
             ))
